### ISSUE TITLE
Add the latest stable Koin 1.x to the comparison

### ISSUE THREAD

**Issue by kirich1409** [Sloy/android-dependency-injection-performance#3]
Hi. Please add Koin the latest stable Koin 1.X to the comparison. Koin 2 based on reflection that will slow it work and the second version of the library on the early stage of development that's why result is can't describe actual usage of Koin in projects..

**Comment by Sloy** [comment]
Hi. Thanks for the comment :)

I believe Koin 2 is not based on reflection by default, that's an optional module that you can add. 

I intentionally updated Koin to 2.0.0 alpha, to see the performance improvements. I wrote this project precisely because of the performance problems in Koin 1.0, which stoped us from using it in production, as you can see here https://github.com/InsertKoinIO/koin/issues/281

So we're really interested in the improvements on 2.0. That's why I updated it even though it's an alpha. If you're concerned about performance, you should not use Koin 1.0 IMHO. 

I hope the explanation is good enough
